# List of training data files
training_data_paths:
- "/home/magics/hdd/sky_ws/skai_universal_forecaster/data/train/run-7/data/data.arrow"
# Mixing probability of each dataset file
probability:
- 1.0
# model_id: google/t5-efficient-base
model_id: /home/magics/hdd/sky_ws/skai_universal_forecaster/data/train/run-8/run-3/checkpoint-5000
max_steps: 50_000 #10_000
save_steps: 5_000 #2_000
learning_rate: 0.001
per_device_train_batch_size: 8 #128 #32
model_type: seq2seq

output_dir: ./data/train/run-8
context_length: 128 #128 #128 #512 #128 #64 
min_past: 64
prediction_length: 32 #8  #32 #64 #16 #16
# random_init: true #true
# this is very tricky, if the scale is too small, the model will not learn
tokenizer_class: "MeanScaleUniformBins"
n_tokens: 4096
tokenizer_kwargs:
  low_limit: 0.6 #0.0 #TODO 0.8
  high_limit: 1.4 #1.2